// Generates docs/movement-metrics.md from the simulator, which reads its
// constants from src/game/vault.ts. Nothing in that document is typed by hand,
// because a movement table typed by hand is a table that is wrong the first
// time anyone touches the controller.
//
//   npm run levels:metrics
import { writeFileSync } from 'fs';
import { C, metrics } from './lib/movement.mjs';
import { trace, plot } from './lib/arcplot.mjs';

const m = metrics();
const t = (n) => (n).toFixed(2);
const frac = (d) => (d / m.running.distance).toFixed(2);

const doc = `# Movement metrics — measured, not derived

Generated by \`npm run levels:metrics\` from [scripts/lib/movement.mjs](../scripts/lib/movement.mjs),
which parses its constants out of [src/game/vault.ts](../src/game/vault.ts) and
simulates the real integration loop. **Do not hand-edit this file.**

Everything is in **tiles** and **frames at 60 fps**. The body is
${t(C.HW * 2)} × ${t(C.HH * 2)} tiles.

## Why these are simulated and not calculated

The arc is not a parabola. Three things bend it away from what the constants
imply, and a level authored against the algebra is authored against a game
that does not exist:

- **The apex band.** While jump is held and \`|vy| < ${C.APEX_BAND}\`, gravity runs at
  half strength. That is a deliberate ~0.3 s crown at the top of every jump,
  and it is where the spark decisions happen.
- **The jump cut.** Releasing jump while rising multiplies \`vy\` by 0.45
  immediately, so height is continuous with hold time, not binary.
- **The air-speed clamp.** Horizontal air control tops out at **5.0 tiles/s**,
  which is *faster* than the ${C.WALK} tiles/s ground walk. The game is quicker in
  the air than on the ground. This is the single most important fact in this
  document and §4 of the principles is built on it.

## The table

| move | height | distance | air time | notes |
|---|---|---|---|---|
| standing jump | **${t(m.standing.height)}** | ${t(m.standing.distance)} | ${m.standing.airFrames}f | the vertical unit |
| running jump | **${t(m.running.height)}** | **${t(m.running.distance)}** | ${m.running.airFrames}f | the horizontal unit |
| short hop (3f held) | ${t(m.shortHop.height)} | ${t(m.shortHop.distance)} | ${m.shortHop.airFrames}f | variable height is real and usable |
| run + flat spark | ${t(m.runDashFlat.height)} | ${t(m.runDashFlat.distance)} | ${m.runDashFlat.airFrames}f | **flat spark buys almost nothing** |
| run + 45° spark | ${t(m.runDashUp.height)} | ${t(m.runDashUp.distance)} | ${m.runDashUp.airFrames}f | the long reach |
| standing + flat spark | ${t(m.standDash.height)} | ${t(m.standDash.distance)} | ${m.standDash.airFrames}f | the correction, from rest |
| wall-jump, per kick | ${t(m.wallJumpGain)} | — | — | unlimited, and free |

| forgiveness | value |
|---|---|
| coyote time | ${m.coyoteFrames} frames |
| jump buffer | ${m.bufferFrames} frames |
| wall-jump latch | ${m.latchFrames} frames (push-out cannot be steered against) |
| corner correction | ${C.CORNER} tiles horizontal |
| spark floor-snap | ${C.DASH_POP} tiles |
| wall-jump reach | ${C.WJ_NEAR} tiles — any wall this close counts, pressed into or not |

| runway | value |
|---|---|
| rest → full walk | **${m.runway} tiles / ${m.runwayFrames} frames** |
| full walk → rest | ${m.skid} tiles / ${m.skidFrames} frames |

**Acceleration is effectively instantaneous.** ${m.runway} tiles of runway is a
quarter of one tile. There is no such thing as a run-up in this game, and any
corridor built to provide one is dead space.

## The arcs, plotted from the simulation

Running jump, held to full height — **${t(m.running.distance)} tiles across, ${t(m.running.height)} up**:

\`\`\`
${plot(trace({ runUp: 30 }))}
\`\`\`

Running jump into a 45° spark at the apex — the longest reach in the game:

\`\`\`
${plot(trace({ runUp: 30, dash: { at: 20, dx: 0.7, dy: 0.7 } }), 'o')}
\`\`\`

## Gap vocabulary

Every distance in a level is written as a fraction of the running jump
(${t(m.running.distance)} tiles). This is the unit.

| gap | tiles | fraction | reading |
|---|---|---|---|
| stroll | ≤ 1.6 | ≤ ${frac(1.6)}× | not a jump; do not spend a beat on it |
| comfortable | 2.7 | ${frac(2.7)}× | landable without thinking. The teaching gap. |
| committed | 3.8 | ${frac(3.8)}× | needs a real jump, held. The workhorse. |
| tight | 4.6 | ${frac(4.6)}× | held to full, no hesitation |
| expert | 5.2 | ${frac(5.2)}× | ~${Math.round((m.running.distance - 5.2) * 60 / 5)}-frame margin — sparing use only |
| **impossible without spark** | > ${t(m.running.distance)} | > 1.0× | must be authored as a spark gap |
| spark gap, comfortable | 6.8 | — | 45° spark, ${t(m.runDashUp.distance)} available |
| spark gap, expert | 8.2 | — | near the ceiling of the move |

| rise | tiles | reading |
|---|---|---|
| step | ≤ 1.0 | walk up; free |
| hop | 1.8 | short hop clears it |
| storey | 2.6 | one full jump, or one wall-kick |
| **over a storey** | > ${t(m.standing.height)} | needs a wall, a spark, or a lantern |
| spark climb | 4.0 | 45° spark reaches ${t(m.runDashUp.height)} |

## The verb list

Four verbs. Everything else is a chain of them.

1. **WALK** — ${C.WALK} t/s ground, 5.0 t/s air. Free.
2. **JUMP** — ${t(m.standing.height)} up, ${t(m.running.distance)} across, variable height, ${m.coyoteFrames}f coyote,
   ${m.bufferFrames}f buffer. Free.
3. **WALL-JUMP / SLIDE** — ${t(m.wallJumpGain)} per kick, ${C.WALL_JUMP_OUT} out, catches at ${C.WALL_SLIDE} t/s fall.
   Free, unlimited, and generous: any wall within ${C.WJ_NEAR} tiles counts.
4. **SPARK** — one charge. ${C.DASH_V} t/s for ${C.DASH_T}s in 8 directions, keeps ${C.DASH_KEEP}
   afterward bleeding over ${C.DASH_CARRY}s. Refills on live stone, on a lit sconce
   or brazier within ${(1.4).toFixed(1)} tiles, and on a censer's crown. **Never** on drank
   stone (\`=\`).

The spark is the only scarce verb. That is the whole economy: three verbs are
free and infinite, one is a single breath you spend and must earn back, so
every interesting decision in the game is *where* you spend it.

## The combos — the actual content

Levels exist to make the player perform these. An obstacle that is cleared by
one verb is not content; it is a speed bump.

| combo | what it buys | how a room asks for it |
|---|---|---|
| **run-jump → land → run-jump** | keeps 5.0 t/s air speed across a chain | landing spots that are also launch spots; no flat between |
| **jump → apex spark (45°)** | ${t(m.runDashUp.distance)} across / ${t(m.runDashUp.height)} up | a gap over 1.0× with a ledge above the far side |
| **spark → wall-jump** | converts the spark's ${C.DASH_KEEP} carry into height | a wall placed at the spark's landing point |
| **wall-jump → wall-jump** | ${t(m.wallJumpGain)} per kick, unlimited climb | a shaft ≤ ${(C.WJ_NEAR * 2 + C.HW * 2 + 1).toFixed(1)} tiles wide |
| **wall-jump → spark** | escapes a shaft sideways at height | a shaft that opens on one side near the top |
| **short-hop → chain** | ${t(m.shortHop.height)} clears a ${1.0} step without losing tempo | low obstacles under a low ceiling |
| **fall → fast-fall → land-jump** | cuts ${C.FAST_FALL - C.MAX_FALL} t/s off a descent, buffered landing | a long drop onto a moving target |
| **censer crown → jump** | a floor where there is none | the ride, over a gutter |

### The two that make this game itself

- **Spark → wall-jump.** The spark keeps ${C.DASH_KEEP} t/s for ${C.DASH_CARRY}s after it ends. A wall
  inside that window converts leftover horizontal speed into a full kick. This
  is the highest-skill chain available and it should be the greedy line in
  most rooms.
- **Landing is refuelling.** Touching live stone refills the spark. So a chain
  of *grounded* beats is a chain of spark opportunities, and a chain of
  *airborne* beats is a single spark spent well. A room chooses which kind of
  sentence it is by where it puts its floors.
`;

writeFileSync('docs/movement-metrics.md', doc);
console.log('docs/movement-metrics.md written');
